[package]
name = "raytracer"
version = "0.0.8"
authors = ["VincentGong <VicentGong@boyaa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"