[package]
name = "raytracer"
version = "0.1.5"
authors = ["VincentGong <VicentGong@boyaa.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
clap = "2.33.0"
pbr = "1.0.0"
image = "0.23.0"